### ISSUE TITLE
Initial Voltage Sensor Support

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#34]

**Comment by tarek20501** [comment]
Done as of c09bd5dfa14ac39840ba84ce9e5e48768ae7c05a waiting for hardware to test.

**Comment by tarek20501** [comment]
Need to validate equations and check the following from the datasheet
* ADC Resolution
* Max Voltage for analog pins

**Comment by tarek20501** [comment]
https://www.mouser.com/datasheet/2/389/cd00237391-1796869.pdf

**Comment by tarek20501** [comment]
- Check ADC resolution of Particle
- Ask Forbes how he got the 3.9 from ESP32 datasheet
- Do Step 2 for Particle

**Comment by RyanL17** [comment]
STM32F205 Family: 12-bit, 10-bit, 8-bit or 6-bit configurable resolution
Particle 2nd Gen Boards: 12-bit
I believe 4095 is used because it starts at 0 (4096 ints) 
3.6V max analog reference voltage

STM32F205 Family Reference Manual:
https://www.st.com/content/ccc/resource/technical/document/reference_manual/51/f7/f3/06/cd/b6/46/ec/CD00225773.pdf/files/CD00225773.pdf/jcr:content/translations/en.CD00225773.pdf

Particle Analog Read Reference:
https://docs.particle.io/reference/device-os/firmware/photon/#analogread-adc-
